apiVersion: v1
kind: Pod
metadata:
  name: romana-services
  namespace: kube-system
  labels:
    app: romana-services
spec:
  hostNetwork: true
  containers:
  - name: romana-datastore
    image: mysql:5
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: romana
    volumeMounts:
    - name: db-path
      mountPath: /var/lib/mysql
  - name: romana-services
    image: quay.io/romana/services:v0.9.3.2
    args:
    # - --cidr=10.0.0.0/8
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: romana
  volumes:
  - name: db-path
    hostPath:
      path: /var/lib/romana/db
